version: '3.9'

services:
  postgres:
    image: postgres:17
    container_name: postgres_container
    ports:
      - "5439:5432"  
    environment:
      POSTGRES_USER: postgres      
      POSTGRES_PASSWORD: 123456  
      POSTGRES_DB: postgres    
    volumes:
      - postgres_data:/var/lib/postgresql/data  

volumes:
  postgres_data:
